config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users , only: %w[index show]
  resources :chats , only: %w[index new show create destroy] do
    resources :messages , only: %w[index create destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  has_many :chat_users, dependent: :destroy
  has_many :users, through: :chat_users

  include Sort
end

app/models/chat_user.rb
class ChatUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/concerns/sort.rb
module Sort
  extend ActiveSupport::Concern

  included do
    scope :recent, -> {order(id: :desc).limit(5)}
  end

  def hello
    puts "hello"
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chat_users
  has_many :chats, through: :chat_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end

  def new
  end

  def show
    @chat = Chat.find(params[:id])
    @messages = @chat.messages
  end

  def create
    @users = User.where(id: [params[:user_id], current_user.id])

    @chat = Chat.new
    @chat.users << @users
    if @chat.save
      flash[:sccess] = "OK"
      redirect_to chat_path(@chat)
    else
      flash[:fail] = "NG"
      redirect_to root_path
    end
  end

  def destroy
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def create
    @message = Message.new(message_params)

    @message.save
    redirect_to chat_path(params[:chat_id])
  end

  def destory
  end

  def message_params
    params.require(:message).permit(:body, :image, :limit_date).merge(chat_id: params[:chat_id],user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %[show]

  def index
    @users = User.all
    flash[:index] ="top pageだよ"
  end

  def show
    @chats = Chat.joins(:users).where(id: @user.id)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/destroy.html.erb
<h1>Chats#destroy</h1>
<p>Find me in app/views/chats/destroy.html.erb</p>

app/views/chats/index.html.erb
<h1>Chats#index</h1>
<p>Find me in app/views/chats/index.html.erb</p>

app/views/chats/new.html.erb
<h1>Chats#new</h1>
<p>Find me in app/views/chats/new.html.erb</p>

app/views/chats/show.html.erb
<h1>Chats#show</h1>
<p>Find me in app/views/chats/show.html.erb</p>


<h3>メッセージ一覧</h3>
 <div class="messages">
   <% @messages.each do |message|%>
     <%= "#{message.user.name}: #{message.body}"%>
     <%if message.image.present?%>
       <%= image_tag message.image&.url%>
     <%end%>
     <br>
   <%end%>
 </div>

<h3>メッセージフォーム</h3>

<%= form_for [@chat, Message.new] do |f|%>

  <%= f.label :body%>
  <%= f.text_area :body%>
  <%= f.file_field :image%>

  <%= f.label :日付 %>
  <%= f.text_field :limit_date, :class => 'datepicker' %>
  <%= f.submit '送信'%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%="user_id: #{current_user&.id}"%>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
    <%= yield %>
  </body>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/destory.html.erb
<h1>Messages#destory</h1>
<p>Find me in app/views/messages/destory.html.erb</p>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= flash[:index]%>

<% @users.each do |user|%>
  <%=link_to "名前: #{user.name}", "/users/#{user.id}"%>
 <br>
<%end%>

app/views/users/show.html.erb
<h1>User<%= @user.id%></h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= @user.name%>

<%= link_to "チャットする", chats_path(user_id: @user.id), method: :post%>

<h3>chat 一覧</h3>
<br>
<% @chats.each do |chat|%>
  <%= link_to "#{chat.chat_user_name(@user)}", chat_path(chat)%>
  <br>
<%end%>